controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

app_ticket_edit:
    path: /ticket/edit/{id}
    controller: App\Controller\TicketController::edit